import Constants from "expo-constants"

const { expoConfig } = Constants

const TWITCH_TOKEN = expoConfig?.extra?.TWITCH_TOKEN
const TWITCH_CLIENT_ID = expoConfig?.extra?.TWITCH_CLIENT_ID
const EXPO_PUBLIC_SPEEDHUB_API = expoConfig?.extra?.EXPO_PUBLIC_SPEEDHUB_API
const EXPO_PUBLIC_SPEEDRUNDOTCOM_API =
  expoConfig?.extra?.EXPO_PUBLIC_SPEEDRUNDOTCOM_API
const EXPO_PUBLIC_SPEEDRUNDOTCOM_API_V2 =
  expoConfig?.extra?.EXPO_PUBLIC_SPEEDRUNDOTCOM_API_V2
const EXPO_PUBLIC_SPLITIO_API = expoConfig?.extra?.EXPO_PUBLIC_SPLITIO_API
const EXPO_PUBLIC_REDDIT_API = expoConfig?.extra?.EXPO_PUBLIC_REDDIT_API
const EXPO_PUBLIC_TWITCH_PARENT_DOMAIN =
  expoConfig?.extra?.EXPO_PUBLIC_TWITCH_PARENT_DOMAIN
const EXPO_PUBLIC_TWITCH_API = expoConfig?.extra?.EXPO_PUBLIC_TWITCH_API

export {
  TWITCH_TOKEN,
  TWITCH_CLIENT_ID,
  EXPO_PUBLIC_SPEEDHUB_API,
  EXPO_PUBLIC_SPEEDRUNDOTCOM_API,
  EXPO_PUBLIC_SPEEDRUNDOTCOM_API_V2,
  EXPO_PUBLIC_SPLITIO_API,
  EXPO_PUBLIC_REDDIT_API,
  EXPO_PUBLIC_TWITCH_PARENT_DOMAIN,
  EXPO_PUBLIC_TWITCH_API,
}
